version: "3.8"
services:
  postgres:
    build: docker/database/postgresql
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_user: postgres
    ports:
      - 60553:5432