spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:60553/postgres
    username: postgres
    password: postgres
    initialization-mode: never
  jackson:
    visibility:
      field: any
      getter: none
      setter: none
  profiles:
    active: development
mybatis:
  config-location: classpath:mybatis-config.xml
