spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: manager_password
    initialization-mode: always
  jackson:
    visibility:
      field: any
      getter: none
      setter: none
mybatis:
  config-location: classpath:mybatis-config.xml
